name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # ---------- Build FRONTEND ----------
      - name: Setup Node (App)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install & Build App
        working-directory: .
        run: |
          npm ci
          npm run build

      # ---------- Build API (TypeScript -> dist) ----------
      - name: Setup Node (API)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: api/package-lock.json

      - name: Install & Build API
        working-directory: ./api
        run: |
          npm ci
          npm run clean
          npm run build

      - name: Verify artifacts
        run: |
          echo "== APP =="
          ls -la dist || true
          echo "== API source =="
          ls -la api || true
          echo "== API dist =="
          ls -la api/dist || true
          echo "== function.json files in api/dist =="
          find api/dist -maxdepth 2 -type f -name "function.json" -print || true
          echo "== host.json =="
          cat api/host.json || true
          echo "== api/package.json =="
          cat api/package.json || true

      # ---------- Deploy ----------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_POND_08869CF10 }}
          action: upload

          # Frontend (byggd ovan)
          app_location: "/"
          output_location: "dist"
          skip_app_build: true

          # API: låt actionen bygga från källan (språket känns igen via api/package.json)
          api_location: "api"
          skip_api_build: false
          api_build_command: "npm ci && npm run clean && npm run build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR env
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_POND_08869CF10 }}
          action: close
          # VS Code-lint vill ibland ha dessa även vid 'close':
          app_location: "/"
          output_location: "dist"